# HTTP Server
server:  
  port: ${PORT:9999}   # HTTP port

spring:
  security:
    user:
      name: admin
      password: admin
    
eureka:
  client:
    registryFetchIntervalSeconds: 5
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
                
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    es.gincol.blog: 'DEBUG'
