server:  
  port: ${PORT:9999}

spring:
  security:
    user:
      name: admin
      password: password
  boot:
    admin:
      discovery:
        ignored-services: arq1-admin-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
                
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    es.gincol.blog: 'DEBUG'
