# HTTP Server
server:  
  port: ${PORT:9999}   # HTTP port

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
     preferIpAddress: true
          
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    es.gincol.blog: 'DEBUG'
