# HTTP Server
server:  
  port: ${PORT:9999}   # HTTP port

spring:
#  security:
#    user:
#      name: admin
#      password: admin
  boot:
    admin:
#      client: 
#        metadata:
#          user:
#            name: ${security.user.name}
#            password: ${security.user.password}
      routes:
        endpoints: env, metrics, trace, jolokia, info, configprops

#security:
#  user:
#    name: client
#    password: client 
    
eureka:
  client:
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

#management:
#  security:
#    enable: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"  
#  endpoint:
#    health:
#      show-details: ALWAYS
                
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    es.gincol.blog: 'DEBUG'
