# HTTP Server
server:  
  port: ${PORT:2222}   # HTTP port

ping:  
  service:
    name: arq1-ping-service
    pingUrl: http://${ping.service.name}/ping/doPing/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
          
logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    es.gincol.blog: 'DEBUG'

management:
  endpoints:
    web:
      exposure:
        include: refresh, info, health, metrics, trace
  endpoint:
    shutdown:
      enabled: true

info:
  version: '@project.version@'
            
swagger:
  basepackage: es.gincol.blog
  
mongeez:
  initialLoadingFile: mongeez.xml  