server:  
  port: ${PORT:2222} 
  
ping:  
  service:
    name: arq1-ping-service
    pingUrl: http://${ping.service.name}/ping/doPing/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
          
management:
  endpoints:
    web:
      exposure:
        include: refresh, info, health, metrics, trace

logging:  
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    es.gincol.blog: 'DEBUG'

swagger:
  basepackage: es.gincol.blog
  
mongeez:
  initialLoadingFile: mongeez.xml  
  